export const homeobjOne = {
    lightBg: false,
    imgStart: false,
    primary: true,
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Marketing agency',
    text: 'Lead generation specialist for online businesses',
    textDescription: 'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals.',
    buttonLabel: 'Get Started',
    img: process.env.PUBLIC_URL + "/images/tech-1.svg",
    alt: 'Tech-Image',
    start: false,
}

export const homeobjTwo = {
    lightBg: true,
    imgStart: true,
    primary: false,
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Marketing agency',
    text: 'Lead generation specialist for online businesses',
    textDescription: 'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals.',
    buttonLabel: 'Get Started',
    img: process.env.PUBLIC_URL + "/images/profile-1.jpg",
    alt: 'Tech-Image',
    start: true,
}

export const homeobjThree = {
    lightBg: false,
    imgStart: false,
    primary: true,
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Marketing agency',
    text: 'Lead generation specialist for online businesses',
    textDescription: 'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals.',
    buttonLabel: 'Get Started',
    img: process.env.PUBLIC_URL + "/images/tech-2.svg",
    alt: 'Tech-Image',
    start: false,
}

export const homeobjFour = {
    lightBg: false,
    imgStart: true,
    primary: true,
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Marketing agency',
    text: 'Lead generation specialist for online businesses',
    textDescription: 'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals.',
    buttonLabel: 'Get Started',
    img: process.env.PUBLIC_URL + "/images/tech-3.svg",
    alt: 'Tech-Image',
    start: true,
}